// <auto-generated />
using IndiaEvents.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndiaEvents.Models.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndiaEventsWebApi.Models.MasterSheets.CodeCreation.VendorCodeGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BenificiaryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChequeDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinanceChecker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IbnNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfscCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitiatorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitiatorNameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MisCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanCardDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanCardName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxResidenceCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorAccount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("vendorCodeGenerations");
                });
#pragma warning restore 612, 618
        }
    }
}
